import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/_assets/globals.css";
import {gsap} from "gsap";
import {ScrollTrigger} from "gsap/ScrollTrigger";
import SmoothScrolling from "@/app/_components/SmoothScrolling";

const inter = Inter({ subsets: ["latin"] });

gsap.registerPlugin(ScrollTrigger);

gsap.defaults({
  ease: "power3.inOut"
});

export const metadata: Metadata = {
  title: "Benjamin — Development",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SmoothScrolling>{children}</SmoothScrolling>
      </body>
    </html>
  );
}
